export default [
  {
    id: 1,
    bandeira:require('../assets/Country_BR.png'),
    idioma: 'Português',
    horario: '08h30 às 09h30',
    data: '12/11/2024',
    modelo: 'Presencial',
    pessoa: 'Gandalf',
    photo: require('../assets/Icon_4.png'),
  },
  {
    id: 2,
    bandeira:require('../assets/Country_EN.png'),
    idioma: 'Inglês',
    horario: '10h00 às 11h00',
    data: '12/11/2024',
    modelo: 'Presencial',
    pessoa: 'Gandalf',
    photo: require('../assets/Icon_4.png'),
  },
  {
    id: 3,
    bandeira:require('../assets/Country_EN.png'),
    idioma: 'Inglês',
    horario: '14h00 às 15h30',
    data: '12/11/2024',
    modelo: 'Presencial',
    pessoa: 'Gandalf',
    photo: require('../assets/Icon_4.png'),
  },
  {
    id: 4,
    bandeira:require('../assets/Country_BR.png'),
    idioma: 'Português',
    horario: '08h30 às 09h30',
    data: '12/11/2024',
    modelo: 'Presencial',
    pessoa: 'Gandalf',
    photo: require('../assets/Icon_4.png'),  },
]