export default [
  {
    id: 1,
    name: 'Albus Dombledore',
    info: 'Professor de inglês | Presencial e Home-office',
    photo: require('../assets/Icon_2.png'),
    registration: 'A010D01',
    account: 'Wizard - Professor',
    email: 'albus.dumbledore@email.com',
    diaSemana: '',
    horario: '',
    modalidade: '',
  },
  {
    id: 2,
    name: 'Merlin',
    info: 'Professor de inglês | Presencial e Home-office',
    photo: require('../assets/Icon_3.png'),
    registration: 'B020D02',
    account: 'Wizard - Professor',
    email: 'merlin.professora@email.com',
    diaSemana: '',
    horario: '',
    modalidade: '',

  },
  {
    id: 3,
    name: 'Gandalf',
    info: 'Professor de inglês | Presencial',
    photo: require('../assets/Icon_4.png'),
    registration: 'C030D03',
    account: 'Wizard - Professor',
    email: 'gan-dalf-778@email.com',
    diaSemana: '',
    horario: '',
    modalidade: '',
  },
  {
    id: 4,
    name: 'Erik Frostheim',
    info: 'Professor de alemão | Home-office',
    photo: require('../assets/Icon_5.png'),
    registration: 'D040D04',
    account: 'Wizard - Professor',
    email: 'erik-fros.157@email.com',
    diaSemana: '',
    horario: '',
    modalidade: '',
  },
  {
    id: 5,
    name: 'Albus Duas-Portas',
    info: 'Professor de inglês | Presencial e Home-office',
    photo: require('../assets/Icon_2.png'),
    registration: 'A010D01',
    account: 'Wizard - Professor',
    email: 'albus.dumbledore@email.com',
    diaSemana: '',
    horario: '',
    modalidade: '',
  },
  {
    id: 6,
    name: 'Merlani',
    info: 'Professor de inglês | Presencial e Home-office',
    photo: require('../assets/Icon_3.png'),
    registration: 'B020D02',
    account: 'Wizard - Professor',
    email: 'merlin.professora@email.com',
    diaSemana: '',
    horario: '',
    modalidade: '',

  },
  {
    id: 7,
    name: 'Gôlfe',
    info: 'Professor de inglês | Presencial',
    photo: require('../assets/Icon_4.png'),
    registration: 'C030D03',
    account: 'Wizard - Professor',
    email: 'gan-dalf-778@email.com',
    diaSemana: '',
    horario: '',
    modalidade: '',
  },
  {
    id: 8,
    name: 'Erick Gelado',
    info: 'Professor de alemão | Home-office',
    photo: require('../assets/Icon_5.png'),
    registration: 'D040D04',
    account: 'Wizard - Professor',
    email: 'erik-fros.157@email.com',
    diaSemana: '',
    horario: '',
    modalidade: '',
  } 
]